"""
SOME/IP transport adapter placeholder.

This adapter is intentionally marked as Protocol Abstraction. It preserves the
same Transport API while deferring runtime middleware binding to vsomeip-based
integration artifacts generated by protocol_adapter.py.
"""

from __future__ import annotations

from typing import Any, Dict

from transport.transport_interface import Transport


class SomeIpTransport(Transport):
    """
    Placeholder transport that defines the integration contract.

    Production wiring is expected through generated vsomeip artifacts:
    - vsomeip_config.json
    - vsomeip_service.hpp/.cpp
    - vsomeip_client.cpp
    """

    def __init__(self, endpoint: str):
        self.endpoint = endpoint

    def send_bms_signals(self, signals: Dict[str, Any]) -> Dict[str, Any]:
        return {
            "error": "SOME/IP runtime not bound in Python path",
            "details": "Use generated C++ vsomeip abstraction artifacts for middleware integration.",
            "transport": "someip",
            "endpoint": self.endpoint,
            "echo_signals": signals,
        }
